[package]
name = "actix-todo"
version = "0.1.0"
authors = ["Martin Lofaj <lofajmatko@gmail.com>"]

[dependencies]
actix-web = "0.6"
futures = "0.2.1"

serde = "1.0.60"
serde_derive = "1.0.60"
serde_json = "1.0.17"

log = "0.4.1"
env_logger = "0.5.10"